name: github_user_finder_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  dio: ^5.3.4
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/ic_launcher.png'

flutter:
  uses-material-design: true